name: Linting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Flake8
      uses: suo/flake8-github-action@v1
      with:
        checkName: lint
